package org.ametiste.redgreen.application.process.simple;

/**
 *
 * @since 0.3.0
 */
public interface SimpleFailoverProcessorMetrics {

    String LINE_NAME = "processor.simple-failover";

    String MAIN_ACTION_NAME = ".main";

    String FAILOVER_ACTION_NAME = ".failover";

    String PERFS_SECTION_NAME = ".performance";

    String TIMING_PERF_SECTION_NAME = ".timing";

    String EVENTS_SECTION_NAME = ".events";

    String ATTEMPTS_EVENT_SECTION_NAME = ".attempts";

    String ERROR_EVENT_SECTION_NAME = ".errors";

    String MAIN_PERF_TIMING = LINE_NAME + MAIN_ACTION_NAME + PERFS_SECTION_NAME + TIMING_PERF_SECTION_NAME;

    String MAIN_EVENT_ATTEMPTS = LINE_NAME + MAIN_ACTION_NAME + EVENTS_SECTION_NAME + ATTEMPTS_EVENT_SECTION_NAME;

    String MAIN_EVENT_ERRORS = LINE_NAME + MAIN_ACTION_NAME + EVENTS_SECTION_NAME + ERROR_EVENT_SECTION_NAME;

    String FAILOVER_PERF_TIMING = LINE_NAME + FAILOVER_ACTION_NAME + PERFS_SECTION_NAME + TIMING_PERF_SECTION_NAME;

    String FAILOVER_EVENT_ATTEMPTS = LINE_NAME + FAILOVER_ACTION_NAME + EVENTS_SECTION_NAME + ATTEMPTS_EVENT_SECTION_NAME;

    String FAILOVER_EVENT_ERRORS = LINE_NAME + FAILOVER_ACTION_NAME + EVENTS_SECTION_NAME + ERROR_EVENT_SECTION_NAME;

}
